### PR TITLE
Fix error on destroy of a direct message

### PR DESCRIPTION
**Pull request by GCorbel**
This is related to https://github.com/sferik/twitter/issues/970

### CODE REVIEW

**Comment by FabienChaynes** [comment]
Seems to be coming from https://github.com/sferik/twitter/commit/a6c4b67cb427f3d1738d81200f20f8e0b2b8b46f#diff-5d38f3bad005d270f8aa5b061db9f290L155

Do you confirm? Are the specs failing with the old version (`perform_requests(:delete, '/1.1/direct_messages/events/destroy.json', ids)`)?

**Comment by GCorbel** [comment]
Yes I confirm this comes from this commit.

Specs are working with the old version. Here is the doc for `pmap` : 

```
# Returns a new array with the results of running block once for every element in enumerable.
    # If no block is given, an enumerator is returned instead.
    #
    # @param enumerable [Enumerable]
    # @return [Array, Enumerator]
```

It's not useful in our case. Let me know if you what I remove it.

**Comment by FabienChaynes** [comment]
Yes, let's just switch to the previous version and remove `pmap` if everything is indeed working properly please.

**Comment by GCorbel** [comment]
Done!

**Pull request merged**
